version: '3.8'

services:
  web:
    build: .
    expose:
      - "5002;5002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  nginx:   # 👈 must be indented same level as web and redis
    image: nginx:alpine
    ports:
      - "5002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  redis-data:
